"""Implementations of orthogonal transforms."""

from __future__ import annotations

from math import sqrt

import numpy as np
import torch
from torch.nn import functional as F

import flowcon.utils.typechecks as check
from flowcon.transforms.base import Transform
from flowcon.utils import torchutils


class OrthogonalBase(Transform):
    pass


class OrthogonalCaley(OrthogonalBase):
    """
    Parameterization of an orthogonal transformation.
    The orthogonal matrix is generated by
    a.) constructing a skew-symmetric matrix
    b.) using the skew-symmetric matrix in a Caley transform.

    https://en.wikipedia.org/wiki/Cayley_transform#Matrix_map

    """

    def __init__(self, n_features: int):
        """Constructor.

        Args:
            features: int, dimensionality of the input.

        Raises:
            TypeError: if arguments are not the right type.
        """
        if n_features < 2:
            raise ValueError(
                "Householder Reflections require at least two dimensions to be nontrivial."
            )
        if not check.is_positive_int(n_features):
            raise TypeError("Number of features must be a positive integer.")

        super().__init__()
        self.n_features = n_features

        self.orth_linear = torch.nn.utils.parametrizations.orthogonal(
            torch.nn.Linear(self.n_features, self.n_features, bias=False),
            orthogonal_map="cayley",
        )

    def forward(self, inputs: torch.Tensor, context: torch.Tensor | None = None):
        return F.linear(inputs, self.matrix()), torch.zeros(inputs.shape[0])

    def inverse(self, inputs: torch.Tensor, context: torch.Tensor | None = None):
        return F.linear(inputs, self.matrix().T), torch.zeros(inputs.shape[0])

    def matrix(self) -> torch.Tensor:
        """Returns the orthogonal matrix that is equivalent to the total transform.

        Costs O(KD^2), where:
        - K is number of transforms
        - D is dimensionality of inputs

        Returns:
            A Tensor of shape [D, D].
        """
        return self.orth_linear.weight


class OrthogonalHouseholderGEQR(OrthogonalBase):
    """
    Parameterization of an orthogonal transformation.
    The orthogonal matrix is generated by
    a.) constructing a skew-symmetric matrix
    b.) using the skew-symmetric matrix in a Caley transform.

    https://en.wikipedia.org/wiki/Cayley_transform#Matrix_map

    """

    def __init__(self, n_features: int):
        """Constructor.

        Args:
            features: int, dimensionality of the input.

        Raises:
            TypeError: if arguments are not the right type.
        """
        if n_features < 2:
            raise ValueError(
                "Householder Reflections require at least two dimensions to be nontrivial."
            )
        if not check.is_positive_int(n_features):
            raise TypeError("Number of features must be a positive integer.")

        super().__init__()
        self.n_features = n_features

        self._A = torch.nn.Parameter(
            torch.randn(self.n_features, self.n_features) / sqrt(self.n_features)
        )

    def forward(self, inputs: torch.Tensor, context: torch.Tensor | None = None):
        return F.linear(inputs, self.matrix()), torch.zeros(inputs.shape[0])

    def inverse(self, inputs: torch.Tensor, context: torch.Tensor | None = None):
        return F.linear(inputs, self.matrix().T), torch.zeros(inputs.shape[0])

    def matrix(self) -> torch.Tensor:
        return torch.linalg.householder_product(*torch.geqrf(self._A))


class OrthogonalHouseholder(OrthogonalBase):
    """
    Parameterization of an orthogonal transform based on a sequence of householder transformations.
    Relies on a custom sequential implementation of the householder projections,
    which might not be optimal in terms of performance.

    https://en.wikipedia.org/wiki/Householder_transformation

    """

    def __init__(self, n_features: int):
        """Constructor.

        Args:
            features: int, dimensionality of the input.

        Raises:
            TypeError: if arguments are not the right type.
        """
        if not check.is_positive_int(n_features):
            raise TypeError("Number of features must be a positive integer.")

        super().__init__()
        self.n_features = n_features
        self.num_transforms = self.n_features

        self.q_vectors = torch.nn.Parameter(self.build_q_vectors(), requires_grad=True)

    def build_q_vectors(self) -> torch.Tensor:
        qv = torch.repeat_interleave(
            torch.eye(self.num_transforms // 2, self.n_features), 2, 0
        )
        if np.mod(self.num_transforms, 2) != 0:  # odd number of transforms, including 1
            qv = torch.cat((qv, torch.zeros(1, self.n_features)))
            qv[-1, self.num_transforms // 2] = 1
        return qv

    def forward(
        self, inputs: torch.Tensor, context: torch.Tensor | None = None
    ) -> tuple[torch.Tensor, torch.Tensor]:
        return batchwise_householder_transform(inputs, self.q_vectors)

    def inverse(
        self, inputs: torch.Tensor, context: torch.Tensor | None = None
    ) -> tuple[torch.Tensor, torch.Tensor]:
        # Each householder transform is its own inverse, so the total inverse is given by
        # simply performing each transform in the reverse order.
        reverse_idx = torch.arange(self.num_transforms - 1, -1, -1)
        return batchwise_householder_transform(inputs, self.q_vectors[reverse_idx])

    def matrix(self):
        """Returns the orthogonal matrix that is equivalent to the total transform.

        Costs O(KD^2), where:
        - K is number of transforms
        - D is dimensionality of inputs

        Returns:
            A Tensor of shape [D, D].
        """
        identity = torch.eye(
            self.n_features, self.n_features, device=self.q_vectors.device
        )
        outputs, _ = self.inverse(identity)
        return outputs


class ParametrizedHouseHolder(Transform):
    """A sequence of Householder transforms.

    This class can be used as a way of parameterizing an orthogonal matrix.
    """

    def __init__(self, q_vectors: torch.Tensor):
        """Constructor.

        Args:
            features: int, dimensionality of the input.
            num_transforms: int, number of Householder transforms to use.

        Raises:
            TypeError: if arguments are not the right type.
        """

        super().__init__()
        self.features = q_vectors.shape[-1]
        self.num_transforms = q_vectors.shape[-2]
        self.q_vectors = q_vectors
        self.reverse_idx = torch.arange(self.num_transforms - 1, -1, -1).to(
            q_vectors.device
        )

    def forward(
        self, inputs: torch.Tensor, context: torch.Tensor | None = None
    ) -> tuple[torch.Tensor, torch.Tensor]:
        return batchwise_householder_transform(inputs, self.q_vectors)

    def inverse(
        self, inputs: torch.Tensor, context: torch.Tensor | None = None
    ) -> tuple[torch.Tensor, torch.Tensor]:
        # Each householder transform is its own inverse, so the total inverse is given by
        # simply performing each transform in the reverse order.
        return batchwise_householder_transform(
            inputs, self.q_vectors[..., self.reverse_idx, :]
        )

    def matrix(self) -> torch.Tensor:
        """Returns the orthogonal matrix that is equivalent to the total transform.

        Costs O(KD^2), where:
        - K is number of transforms
        - D is dimensionality of inputs

        Returns:
            A Tensor of shape [D, D].
        """

        identity = torch.eye(self.features, self.features).to(self.q_vectors.device)
        if len(self.q_vectors.shape) > 2:
            identity = torch.repeat_interleave(
                identity[None, ...], self.q_vectors.shape[0], 0
            )
        outputs = []
        for i in range(self.features):
            outputs_, _ = self.inverse(identity[..., i, :])
            outputs.append(outputs_.unsqueeze(-2))
        outputs = torch.concatenate(outputs, -2)
        return outputs


def batchwise_householder_transforms_nodet(
    inputs: torch.Tensor, q_vectors: torch.Tensor
) -> torch.Tensor:
    """Apply the sequence of transforms parameterized by given q_vectors to inputs.

    Costs O(KDN), where:
    - K is number of transforms
    - D is dimensionality of inputs
    - N is number of inputs

    Args:
        inputs: Tensor of shape [N, D]
        q_vectors: Tensor of shape [N, K, D]

    Returns:
        A tuple of:
        - A Tensor of shape [N, D], the outputs.
        - A Tensor of shape [N], the log absolute determinants of the total transform.
    """
    squared_norms = torch.sum(q_vectors**2, dim=-1)
    # inputs2 = inputs.unsqueeze(0)

    # Compute batchwise dot product: [K, N] = einsum("kd,nd->kn", q_vectors, inputs)
    # dot_products = torch.einsum("ndk,nd->nk", q_vectors, inputs)

    outputs = inputs
    for i in range(q_vectors.shape[-2]):
        q_vector = q_vectors[..., i, :]
        squared_norm = squared_norms[..., i].unsqueeze(-1)
        temp = torchutils.batchwise_dot_prod(outputs, q_vector)  # Inner product.
        # temp = torch.einsum("...i, ...i -> ...", outputs, q_vector)
        temp = temp.unsqueeze(-1) * ((2.0 / squared_norm) * q_vector)
        outputs = outputs - temp
    return outputs


def batchwise_householder_transform(
    inputs: torch.Tensor, q_vectors: torch.Tensor
) -> tuple[torch.Tensor, torch.Tensor]:
    """Apply the sequence of transforms parameterized by given q_vectors to inputs.

    Costs O(KDN), where:
    - K is number of transforms
    - D is dimensionality of inputs
    - N is number of inputs

    Args:
        inputs: Tensor of shape [N, D]
        q_vectors: Tensor of shape [K, D]

    Returns:
        A tuple of:
        - A Tensor of shape [N, D], the outputs.
        - A Tensor of shape [N], the log absolute determinants of the total transform.
    """
    outputs = batchwise_householder_transforms_nodet(inputs, q_vectors)
    batch_size = outputs.shape[0]
    logabsdet = inputs.new_zeros(batch_size)
    return outputs, logabsdet
