# Dockerfile-pytorch1.13.1
FROM pytorch/pytorch:latest

WORKDIR /app

RUN apt update && apt install build-essential -y --no-install-recommends

# Copy the source code and install the packagepdoc
COPY . /flowc
RUN pip install /flowc

CMD ["/bin/bash"]

EXPOSE 8080

