name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v10
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Install project
        env:
          UV_TORCH_BACKEND: cpu
        run: uv pip install --system -e ".[docs]"

      - name: Build documentation
        run: |
          pdoc3 flowcon -o docs/ --html --force
          mv docs/flowcon/* docs
          rmdir docs/flowcon

      - uses: actions/upload-artifact@v5
        with:
          name: generated-site
          path: docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
